### ISSUE TITLE
Release tests v4.22

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3571]
## The basics
- [x] Smoke tested the Demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro
- [x] Smoked tested the app on a mobile device

**Comment by ackernaut** [comment]
### Demo borks when creating a task
- In the Demo, unauthenticated, advance to the Discuss phase
- Attempt to add a task card
- See the developer alert message in the main area
```
instrument.js:102 TypeError: Cannot destructure property 'preferredName' of 'u' as it is undefined.
    at NullableTask.tsx:23
```

**Comment by ackernaut** [comment]
### Accepting team invite via notif menu breaks
- Create a new team with User A
- Invite a User B via email
- User B taps to accept the invite in the notification menu
- See a full page fail, “alerted the developers”
- See in the browser console:
```
instrument.js:102 TypeError: Cannot destructure property 'id' of 'n' as it is undefined.
    at DashNavList.tsx:50
```

**Comment by ackernaut** [comment]
### Task card timestamp flicker
- Tap the timestamp toward the left (start of) the string. It quickly flickers between “Editing…” to the toggled state
- Tap the timestamp toward the right (end of) the string. It gets stuck on “Editing…”

![task-timestap-flicker](https://user-images.githubusercontent.com/307286/74279362-6343e280-4ce0-11ea-804e-a6b79dd7c6a6.gif)

**Comment by ackernaut** [comment]
### Task assign/mention notification and snackbar
- Two users are on the same team dashboard
- One user assigns or mentions the other user on a task card
- The other user gets a notification and a snackbar
- I think the intent was that a user doesn’t get notified if they are in the same meeting or on the same team dashboard

**Comment by ackernaut** [comment]
### Notification menu items too wide on mobile
- Check out the notification menu on a mobile device
- The menu has a horizontal overflow. I suspect the items with a task card are causing the overflow. Or maybe there’s a min-width on the menu container IDK.
- In a responsive window the menu is positioned to fill the entire view. On mobile, it seems anchored on the right side.
#### Android device
![Screenshot_20200211-152209](https://user-images.githubusercontent.com/307286/74280772-cafb2d00-4ce2-11ea-97ce-a1a47250178e.png)

#### Android simulator in Chrome
![Screenshot 2020-02-11 15 25 52](https://user-images.githubusercontent.com/307286/74280810-dc443980-4ce2-11ea-9d71-b1e9cf58a9c4.png)

**Comment by mattkrick** [comment]
@ackernaut all fixed up!

**Comment by ackernaut** [comment]
@mattkrick thanks!

- ✅ Timestamp toggle looks good
- ✅ Team invite in notification menu works
- Not sure if you want to fix [this snackbar/notification behavior for task mentions/assignments]

Otherwise, LGTM!
