### ISSUE TITLE
v5.3.0 release checklist

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3728]
## The basics
Run through this list at least once:
- [x] Smoke tested the Demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [ ] Smoke tested the Retro meeting with 2 players
- [ ] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [ ] Upgraded to Pro
- [ ] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)

## What’s changed
- [x] demo discussion topics no longer concatenated together
- [ ] new meeting snackbar appears
- [x] add team button appears on dashboard leftnav using iOS mobile

### custom voting
- [ ] During the vote phase, you click the thumbs down or thumbs up on a topic to unvote/vote
- [ ] The color for controls is appropriate for the collapsed topics
- [ ] The color for controls is appropriate for expanded topics
- [ ] if the control is disabled, it's light gray
- [ ] as facilitator, you can click the vote settings to open a menu
- [ ] you can increase the total votes up to 12 or down to 1
- [ ] if total votes is 5 and a meeting member has spent 4, the facilitator cannot decrease the total votes below 4. They get an error saying so
- [ ] if max topic votes is 3 and a meeting member has spent 3, the facilitator cannot decrease the max topic votes below 3. They get an error saying so
- [ ] if decrementing the max votes results in a value that is less than the topic votes, both are decremented
- [ ] if incrementing the topic votes results in a value that is greater than the max votes, both are incremented
- [ ] The number of team votes remaining is derived from the number of team members checked in. someone is checked in if they have visited the meeting (if no check in round)

**Comment by jordanh** [comment]
# Test Cycle 2
## The basics
Run through this list at least once:
- [ ] Smoke tested the Demo, unauthenticated
- [ ] Smoke tested the Retro meeting with 2 players
- [ ] Smoke tested the Action meeting with 2 players
- [ ] Upgraded to Pro
- [ ] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)

## What’s changed
- [ ] new meeting snackbar appears

### custom voting
- [ ] During the vote phase, you click the thumbs down or thumbs up on a topic to unvote/vote
- [ ] The color for controls is appropriate for the collapsed topics
- [ ] The color for controls is appropriate for expanded topics
- [ ] if the control is disabled, it's light gray
- [ ] as facilitator, you can click the vote settings to open a menu
- [ ] you can increase the total votes up to 12 or down to 1
- [ ] if total votes is 5 and a meeting member has spent 4, the facilitator cannot decrease the total votes below 4. They get an error saying so
- [ ] if max topic votes is 3 and a meeting member has spent 3, the facilitator cannot decrease the max topic votes below 3. They get an error saying so
- [ ] if decrementing the max votes results in a value that is less than the topic votes, both are decremented
- [ ] if incrementing the topic votes results in a value that is greater than the max votes, both are incremented
- [ ] The number of team votes remaining is derived from the number of team members checked in. someone is checked in if they have visited the meeting (if no check in round)

**Comment by jordanh** [comment]
@mattkrick when I upgraded, I didn't get a confetti cannon. Curious! Not going to hold up the release tho.

**Comment by mattkrick** [comment]
just tested the cannon on staging & it worked for me, but i remember sometimes it is a little slow...
