### ISSUE TITLE
v.5.4.0 Release Test Checklist

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3757]
## The basics
Run through this list at least once:
- [x] Smoke tested the Demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)

## What’s changed

When a meeting is completed is desktop view:
- [x] the columns in the group/vote/discuss phase are full height in desktop view
- [x] the columns in the group/vote/discuss phase are full height in mobile view

When a meeting is not completed in desktop view
- [x] the columns avoid the bottom bar in desktop view

When a meeting is not completed in mobile view
- [x] the bottom bar is fixed to the bottom with the address bar present
- [x] it's still fixed when scrolled down & the address bar goes away
- [x] the carousel dots to swipe between columns are present above the bottom bar

**Comment by jordanh** [comment]
All tests passed! Only note: The demo's Reflect phase now takes a good while before one is allowed to advance. Let's watch user behavior...we might want to speed up the rate at which the bots enter in their cards.
