### ISSUE TITLE
Release v5.7.0 🏁

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3849]
## The basics
Run through this list at least once:
- [ ] Smoke tested the Demo, unauthenticated
- [ ] Created an account
- [x] Verified invite via mass link works
- [ ] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the Retro meeting with 2 players
- [ ] Smoke tested the Action meeting with 2 players
- [ ] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [ ] Upgraded to Pro
- [ ] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
## What’s changed
- [ ] #3848 notification summary email updates
- [ ] #3847 persist email for analytics
- [ ] #3846 add new Segment events
- [ ] #3842 fix Retro summary email topic links
- [ ] #3838 refactor emails to support Google
- [ ] #3837 remove waits from tests
- [ ] #3823 control to confirm advancing a meeting

**Comment by ackernaut** [comment]
### The demo doesn’t start off on the right foot
- Open a new incognito window in Chrome
- Go to the Demo on staging
- Note that the kick-off dialog doesn’t appear, the Tips menu doesn’t pop up automatically, and you can’t add reflections
- Refresh and you can move along through the Demo without any apparent problems

**Comment by ackernaut** [comment]
### The email verification doesn’t arrive to the inbox
- Using a Parabol email address, try signing up
- See the message: `Verification required. Check your inbox.`
- The email doesn’t arrive

**Comment by jordanh** [comment]
Released
