### ISSUE TITLE
Release tests v5.8.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#3864]
## The basics
Run through this list at least once:
- [x] Smoke tested the Demo, unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notification
- [x] Added GitHub, verified issue created
- [x] Added Jira, verified issue created
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
## What’s changed
- [x] #3722 Group phase color prompts
- [x] #3850 Rename check-in to icebreaker
- [x] #3865 Moved the invitation shortlink to the env

**Comment by ackernaut** [comment]
### A fatal error when accepting the email invite using the snackbar
- User A sent an email invite
- User B accepted the invite using the snackbar
- It appeared that the invitation redirected to a meeting URL
- The fatal error screen persisted even after refresh
- I sent in a feedback note to [this issue in Sentry](https://sentry.io/share/issue/d86e08dd89644e3d84b67f3389796b8b/)
- I tried the steps again and I didn’t have the problem

**Comment by ackernaut** [comment]
### Creating a new account from the demo, saw fatal errors in the timeline view
- I created an account from the demo
- I saw the 2 Report Feedback buttons in the main timeline area and the sidebar
- I refreshed and everything is normal
- See [the issue in Sentry](https://sentry.io/share/issue/2fa800a985f14ae193503ca81a988f2c/)

**Comment by ackernaut** [comment]
### Tapping the Export to CSV in the demo summary
- As I user I either get redirected to sign in or I get a fatal error
- See [the issue in Sentry](https://sentry.io/share/issue/189c413834864d7ba8cdecfc8e4b47d6/)

**Comment by ackernaut** [comment]
### I have active meetings (in the menu) but I get a fatal screen
- I have many active meetings in the upper right menu
- I tap on one and get the completely fatal screen at the meeting URL
- Here’s [the issue in Sentry](https://sentry.io/share/issue/d86e08dd89644e3d84b67f3389796b8b/)

**Comment by ackernaut** [comment]
@mattkrick should I make an issue for [Tapping the Export to CSV in the demo summary](https://github.com/ParabolInc/parabol/issues/3864#issuecomment-632152721) — it’s possible to get to a bad URL that doesn’t get redirected

**Comment by ackernaut** [comment]
### Backing up production data & managing data on staging
- We’ve updated how we manage databases
- The steps in the Agile Product Workflow policy need to be updated
- We need to check and add SSH access to the production backups remote

**Comment by mattkrick** [comment]
> Creating a new account, saw fatal errors in the timeline view

- this is caused because `viewer` is null
- viewer is `null` because instead of fetching the query, it's using a cached value
- the cached value it's using comes from the `useCachedEmail`, where viewer is null when the fetch is triggered when not logged in
- why does relay treat useCachedEmail.viewer equivalent to DashboardRoot.viewer? that's the big question

**Comment by ackernaut** [comment]
🕵️ nice work MK

**Comment by ackernaut** [comment]
It looks like MK’s fix via PR #3872 patched us up re: https://github.com/ParabolInc/parabol/issues/3864#issuecomment-632150451
