### ISSUE TITLE
Release tests v5.14.0 🏁

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4073]
## The basics
Run through this list at least once at [staging](https://action-staging.parabol.co):
- [x] Smoke tested the [Demo](https://action-staging.parabol.co/retrospective-demo), unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works (Team > Invite Button > Invite Link, visit URL in an incognito window)
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notifications (use `#t_product_actiontime`)
- [x] Added GitHub, verified issue created (use `ParabolInc/publictestrepo`)
- [x] Added Jira, verified issue created (use `parabol-2`)
- [ ] Smoke tested the Retro meeting with 2 players
- [ ] Smoke tested the Action meeting with 2 players
- [ ] Smoke tested cards on the dashboard
- [ ] Created a 2nd team
- [ ] Created a 2nd organization
- [ ] Upgraded to Pro (Credit card number: `4242 4242 4242 4242`, expiration date: any month in the future, CVC: `123`)
- [ ] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
### Added
- Shared Templates (#3942)
- DB tables for TemplateDimension and TemplateScale (#4042)
- Archived Items Checkbox on Task View (#4035)

### Fixed
- Refactor CustomPhaseItem to ReflectPrmpt (#4053)
- Disabled editing and due date slection on archived cards (#4047)
- Segment client initated events (#3942)
- Summaries show groups even if meeting was ended early (#3956)
- Menu navigation keyboard shortcuts wrap around (#4056)

**Comment by ackernaut** [comment]
### Task updates not showing until refresh
This seems to be happening with tasks in all contexts. Changes from a user A won’t show for a user B until user B refreshes the browser:
- Add a task in a thread
- Add a task in a kanban column
- Update a task in a kanban column
