### ISSUE TITLE
🏁 Release tests v5.20.0

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4207]
## The basics
Run through this list at least once at [staging](https://action-staging.parabol.co):
- [x] Smoke tested the [Demo](https://action-staging.parabol.co/retrospective-demo), unauthenticated
- [x] Created an account
- [x] Verified invite via mass link works (Team > Invite Button > Invite Link, visit URL in an incognito window)
- [x] Verified invite via email works
- [x] Added Slack, verified meeting notifications (use `#t_product_actiontime`)
- [x] Added GitHub, verified issue created (use `ParabolInc/publictestrepo`)
- [x] Added Jira, verified issue created (use `parabol-2`)
- [x] Smoke tested the Retro meeting with 2 players
- [x] Smoke tested the Action meeting with 2 players
- [x] Smoke tested cards on the dashboard
- [x] Created a 2nd team
- [x] Created a 2nd organization
- [x] Upgraded to Pro (Credit card number: `4242 4242 4242 4242`, expiration date: any month in the future, CVC: `123`)
- [x] Smoke tested the app on a mobile device (e.g. navigate between views, smoke test a Retro meeting, etc.)
### Added
- [x] Remove shared templates by archived teams #4201 
- [x] Added tab access for due date #4135
- Poker Jira front-end (behind feature flag) #4158
### Changed
- [x] New user task view #4105
- [x] Multi-connection user presence with Redis #4147
- Bump GraphQL to v15 #4193
### Fixed
- [x] Bug fix for first item in menu #4200
- Filter out teamIds in backup organization #4221
- [x] Assign team task card to viewer #4223

**Comment by ackernaut** [comment]
### Empty assignment menu in demo
- [ ] Start the demo
- [ ] Advance to the Discuss phase
- [ ] Note that the assignment menu is empty when tapping on the owner toggle

**Comment by ackernaut** [comment]
### Assignment menu regression
- [ ] Open the task assignment menu
- [ ] See that the list of possible assignees includes the current owner
- We should filter the current owner from the list.

**Comment by ackernaut** [comment]
### User filter missing label
- [ ] Filter the task view by a single team and all team members
- [ ] The user filter only has an icon and no label
- Does it make more sense to put ‘All team members’ like when we put ‘My teams’ or ‘All teams’. Should it always say ‘All teams’ instead of ‘My teams’?
![Screen Shot 2020-09-30 at 15 20 57](https://user-images.githubusercontent.com/307286/94735790-e29a2b00-0330-11eb-8d19-38baec4bfd34.png)
![Screen Shot 2020-09-30 at 15 21 03](https://user-images.githubusercontent.com/307286/94735793-e332c180-0330-11eb-8d81-7f6e6b65bd22.png)
![Screen Shot 2020-09-30 at 15 21 14](https://user-images.githubusercontent.com/307286/94735796-e332c180-0330-11eb-80dd-82c49ffe83b5.png)

**Comment by ackernaut** [comment]
### Focused cards and tabbing through controls
When I tab into a card (on the description or on one of the menu toggles) should the calendar, integration, and status menu icons all be visible, like when hovering? As of now the calendar icon only shows when the description is focused and/or on hover. I can only tab to other menu toggles if they’re visible when hovering the card.

**Comment by tianrunhe** [comment]
I pushed a fix for the "**User filter missing label"** bug.

**Comment by ackernaut** [comment]
All three items were fixed above, pressing on!
