### ISSUE TITLE
Estimate Phase Burndown

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4360]
- [x] add final score to the sidebar if single dimension
- [x] @ackernaut if there are multiple dimensions, what do we show on the sidebar? We need something that shows partial progress, like "hey, i'm not done yet, click me"
- [x] design final score export control via #4362 
- [x] implement final score export control with jira field mapper
- [ ] get a list of tilts & radii for given screen widths & total cards @ackernaut via #4314 
- [x] add initial card spread animation
- [x] add peeking to voted row animation
- [x] add voted row to revealed rows animation
- [x] minicards support a label of `WW` (autoresize font size?) via #4362
- [ ] add progress bar to reveal votes button via #4350 
- [x] clicking a grouped row minicard sets the value in the final score row (does it fill in the value AND submit or just fill in? I think it submits, too. we'll consider this a power move that only takes a single click)
- [x] change logo in active meeting dropdown
- [x] autofocus final score input when reveal votes is clicked
- [x] ~~inactive dimensions are not clickable (a mask is put over them all)~~ won't fix. that makes it impossible to drag to swipe
- [x] single-dimension templates are not swipeable & don't have the 3 dots
- [ ] typing "X" in the finalScore doesn't treat it like 🚫  (stuck on the Template Scale UI PR to avoid merge conflicts)
- [x] optimistically add estimate stage(s) when adding issue to scope (lag is real bad without it)
- [x] start a new meeting & get to first estimate stage w/o refresh
- [x] ~~verify we can write to the default final score field before setting it~~ we just use a friendly error message now
- [x] catch the horrible Jira error for not being able to write to a field & give something friendlier
- [x] can only the facilitator add to the scope? If so what should others see during the scope phase? Checkboxes look clickable to participants but throw a silent error? ‘Not meeting facilitator’
- [x] if there are many revealed rows, the column or view can be scrolled
- [x] pass cards are only created for checked in meeting members, not all team members when "reveal votes" is clicked

**Comment by ackernaut** [comment]
>if there are multiple dimensions, what do we show on the sidebar?

For now, I say nothing. We learn and spin our wheels later instead of now. I also think we hide the total for now when dealing with multiple dimensions. Other bad ideas: we show XX/XX for 2. We show a ballot icon for 3+ and when they hover the item they see the score in a popover? What this question makes me wonder is how and where to show the scores in general when there are multiple. It’ll show in the summary. Should it show as some minimal meta on the story stage regardless of what column you’re looking at?

>minicards support a label of WW (autoresize font size?)

We could get the character count, 1 or 2, and set a font size for that. We bump the size down 1-2px for 2 chars. It’s what I do for the overflow badge based on length. +2-9 uses a bigger fontsize than GTE +10

**Comment by mattkrick** [comment]
the popover idea is clutch. how about this?
- 1 dimension: show the score
- 2+ dimensions: show the first score + ... and when you mouse over it, it shows a tooltip. e.g. "3...". tooltip: "3 | 5 | ?" 

i think we can do better than char count, because e.g. II is OK to show big, but WW will need to shrink. we have textarea-auto-resize, we can use that or similar for an input field i think.

**Comment by ackernaut** [comment]
Re: nav item scores, whatever we do I want it to be clean. Would it be too much for the tooltip to say ‘Effort: 3, Value: 8’? Many dimensions could get ugly but probably anything 2+ is already an edge case for the short term.

Re: the char count is cheap and fast. I’m okay with automagic if the time is to be spent.

**Comment by ackernaut** [comment]
I added some issues to the list above

**Comment by ackernaut** [comment]
Added
>If votes are revealed and I voted, if I expand the deck and remove my vote (by tapping the card that is raised), I should get added to the Pass row, maybe even raise the Pass card for my deck at this point?

**Comment by mattkrick** [comment]
i think i modeled the mapper wrong.
it's possible someone has multiple jira cloudIds associated with their account.
given the dimension & the service, we can't deterministically pick the field.
that's because the first story _could_ live on cloud A & the 2nd on cloud B.
therefore, the fieldId is a function of dimensionId AND cloudId.

Today, the Stage field `serviceTaskId` is a composite key that includes both the cloudId & issueKey.
I wonder if promoting cloudId to being its own entity is worth it. maybe something like `serviceId`.
That would improve the mental model because each service-oriented resolver needs both the service AND serviceId.

**Comment by mattkrick** [comment]
> Peeking to voted row animation
flying in from the right is waaaay too busy. looks bad. putting it in the middle isn't great because where exactly in the middle?
putting it on the left side could feel a lot better.
