### ISSUE TITLE
Poker Meeting Beta Burndown

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4382]
Here's the list of things to do before beta:

- [ ] Support different deck sizes & adjust the radius & tilt for each (#4314 => #4408)
- [x] Add a meeting summary (#4165)
- [ ] Support editing poker template scales, special handling of no-vote on final value (#4366)
- [ ] Support Parabol Tasks (#4359, #4261)
- [x] Add Progress Bar to Reveal Votes (#4392, designed in #4350)
- [ ] Test edge cases (#4369)
