### ISSUE TITLE
Spotlight implementation

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5105]
This is an implementation issue for the designs explored and proposed on #4952. 
For an overview of the feature, [please watch this Loom recording](https://www.loom.com/share/4e8f8b4e12e8417b8675e994b06d3cec). You can also [review the Figma source file](https://www.figma.com/file/u5bdWUn9hxkdvS2YOYDnXU/Spotlight?node![image](https://user-images.githubusercontent.com/3276087/124194838-e0672780-da8e-11eb-80a6-51475eb3df8d.png)id=85%3A3810).

#### For the new Spotlight modal:
![image](https://user-images.githubusercontent.com/3276087/124196082-52407080-da91-11eb-95e6-aa854c738102.png)

- [ ] On desktop, the new spotlight modal is responsive and takes as much space as possible, but stays clear of the meeting sidebar, the phase header, and the meeting controls.
- [ ] On mobile, the modal takes up the available space between the meeting header on top, and the meeting controls at the bottom.
- [ ] The modal has a heading/title that says "Find similar reflections". This text is set in `Slate 800 #2D2D39`, 16px size and bold.
- [ ] There is a `✗` button aligned to the top-right corner of the modal. The button uses the `close` icon from the Material icons library, at 24px size. The button is set to `Slate 600 #82809A` when resting, and changes to `Slate 800 #2D2D39` when hovered and/or focused. Pressing this button or pressing <kbd>esc</kbd> closes the modal and cancels the action.
- [ ] There is a 16px wide padding all around the modal, both on mobile and desktop.
- [ ] The modal is divided in two sections: at the top there is a section for the "source" reflection on which we are performing the search, and below it a section for the "results" reflections. The top section has a background color of `Slate 100 #F8F7FC`. The bottom section is `White #FFFFFF`.
- [ ] The modal has the default elevation (drop-shadow) we use for other modals/pop-ups.

#### For the new 'Find similar' option in reflection cards:
![121957538-28185000-cd28-11eb-9723-099e2e9fee6b](https://user-images.githubusercontent.com/3276087/124197031-435abd80-da93-11eb-813f-cca294fadb8a.gif)

- [ ] Reflection cards in the Group phase show a 'Find similar' option when hovered (see gif above). The button is aligned to the bottom-right corner of the card, keeping a distance of `2px` from each side. The button uses the `search` icon from the Material library set to `Slate 700 #444258`.
- [ ] On desktop, when the card is hovered, the 'Find similar' button appears with a white background set with a opacity of 75%.
- [ ] When the 'Find similar' button is hovered, the background is set to a solid `Slate 300 #E0DDEC` and a tooltip appears with the legend "Find similar". 
- [ ] On mobile, the button on its hovered state (white semi-transparent background) is always visible.

#### Seeing results:
![image](https://user-images.githubusercontent.com/3276087/124506649-be70ec00-dd91-11eb-8597-11019b95012f.png)
![image](https://user-images.githubusercontent.com/3276087/124508282-3db3ef00-dd95-11eb-86fd-db32478a58b5.png)

- [ ] The selected reflection appears at the top of the modal and centered.
- [ ] Bellow the selected reflection card is a search field with placeholder text "Search for keywords...". The search field is vertically offset so it appear right between the two sections of the modal.
- [ ] Below on the bottom section, we display the results that match the source reflection card. If necessary, we can display a loading animation while the search is performed. We can use the same loading graphic we use elsewhere in the app, like when a meeting is loading.
- [ ] Results should be ordered by relevance, with the highest ranking cards at the top of the group of results. 
- [ ] Results should be arranged in a masonry style (we can use CSS Grid or whatever makes more sense here).
- [ ] If needed (and most likely on mobile), the results section can overflow and allow for vertical scrolling when results don't fit.

#### Grouping reflections
![121966195-d1b10e80-cd33-11eb-9525-1a23e5baa97b](https://user-images.githubusercontent.com/3276087/124507176-e0b73980-dd92-11eb-950e-f951d804f0cf.gif)

- [ ] The source reflection card can be dragged and dropped on top of another card from the results (see example above). When this action ends, the grouping action is shown and then the Spotlight modal is closed.
- [ ] Cards from the results section and also be dragged and dropped on the source card on the top. This action does not close the modal. I can perform this action as many times as needed, or until I run out of cards.
- [ ] Cards from the results section cannot be dragged onto each other. Only from source → results, or results → source.

#### Groups in results
![image](https://user-images.githubusercontent.com/3276087/124507541-95515b00-dd93-11eb-91c0-74b42d47e8f4.png)

- [ ] If the results include any reflections that are already in a group of cards, we display the default group component and show the highest ranking card on top ([pending we can clarify some edge cases](https://github.com/ParabolInc/parabol/issues/4952#issuecomment-868730643)). 
- [ ] Groups can be interacted with the same way they are in any other place of the app.

#### Searching
![image](https://user-images.githubusercontent.com/3276087/124507787-29232700-dd94-11eb-8bd3-0469654f3c0c.png)

- [ ] At any moment the user can perform a search action via the search field. 
- [ ] Searching replaces any previously shown results with new ones bases on the search input.
- [ ] Keyword matches are highlighted (see mockup above) with `Gold 200 #FADC9E`.
- [ ] Group titles can also be highlighted.

#### No results
![image](https://user-images.githubusercontent.com/3276087/124508014-a3ec4200-dd94-11eb-9295-d89df0c228d6.png)

- [ ] If no results are available, either via the 'Find similar' button or via a search action, we display an empty state message (see image above). [Figma source assets here](https://www.figma.com/file/u5bdWUn9hxkdvS2YOYDnXU/Spotlight?node-id=144%3A538).

### Estimated effort:
80 hours

**Comment by enriquesanchez** [comment]
@mattkrick Tried to keep the AC digestible by separating it into sections. Let me know if there's anything you think needs a closer look. Also feel free to edit or update it.

**Comment by ackernaut** [comment]
@enriquesanchez nice work breaking this down! The animation of adding the source card to a results card or group and closing the dialog is 🔥 I’m curious about the ability to group as many results cards onto the source card. Does the user close when they’re satisfied? Then, that new group animates into place, like the group formed when the source card is added to a results card or group? Will folks know how to end the action, or expect it to close automatically? I like that you could quickly build a larger group based on the results since they’re all in one place. I suppose if the group forms in that top space there’s some sort of feedback. Excellent work 👏

**Comment by mattkrick** [comment]
Closing in favor of the other smaller issues
