### ISSUE TITLE
Meeting phase reminders: New Time popup

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5216]
This is a sub-issue for #4994. 

- [Figma file for reference.](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?node-id=125%3A527)

# The new Time popup
![image](https://user-images.githubusercontent.com/3276087/126847877-76290e13-2046-4c30-ad7c-e3d43445abe6.png)

AC:

- [ ] To fit all the new functionality, the Time popup is now `360px` wide.
- [ ] The new Time popup maintains the two tabs we currently have: `Timer` and `Time limit`, but we now have a text label next to each icon.
- [ ] When opened, the Time popup starts by having the `Timer` tab (the left one) active. This is a change from current behavior, where the right tab is active when opened instead. 
- [ ] The `Timer` tab is updated with a new field label 'Set a timer for this stage:` followed by a select field that is focused and has the first item from the dropdown pre-selected (5 minutes).
- [ ] Activating the select field offers the same list of options we currently support (from 1 to 7 minutes).
- [ ] Below the select field is a button `Start timer` set in `Sky 500 #329AE5`. Activating this button starts the timer. (Same as current behavior).

![image](https://user-images.githubusercontent.com/3276087/126847482-f5a96c78-2eb3-426f-8a4c-04527e9b5ebd.png)

- [ ] The `Time limit` tab starts with the label `Time limit for this stage` and is followed by a `date` field.
- [ ] The `date` field is pre-filled with a sensible default (like we currently do) and contains the icon `event` aligned to the right of the field.
- [ ] Activating the `date` field opens a [date and time selector](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?node-id=125%3A778).

![image](https://user-images.githubusercontent.com/3276087/126848682-20bddb26-012f-4d15-9e0e-b2b594fd2fae.png)

- [ ] The date selector is similar to what we currently have, but it adds a time select just below the calendar component. The user can change any of these values and select `Confirm` or `Cancel` below.
- [ ] Below the new `date and time` field is the same checkbox `Notify team via Slack` that we currently have followed by the also current `Start time limit` button.
- [ ] The `Start time limit` button is set to `Sky 500 #329AE5` for background, and `#FFFFFF` for text..
- [ ] If a time limit has been set, the button changes its label to `Clear time limit` and is now set to `Slate 300 #E0DDEC` for background and `Slate 700 #444258` for text. This ends the time limit previously set.
- [ ] If instead the facilitator updates the date and time field, the button's label changes to `Update time limit`.
- [ ] Below, and separated by a `1px` line set in `Slate 300 #E0DDEC` is the new reminders component.
- [ ] It contains the label `Send a reminder in Slack:`.
- [ ] The `reminders` field cannot be set until the facilitator starts a time limit first. This means the `+ Add reminder` button is disabled and in that scenario we show the legend `Please start a time limit before adding a reminder.`
- [ ] If a time limit has been set, then the legend is not shown and the `+ Add reminder` button becomes active. See #5221 for follow up.

EE: 40 hrs
