### ISSUE TITLE
Task details: editing fields

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5367]
This is an implementation issue for #5063.

See related issues for more context:

1. #5366 
2. #5367 (**this issue**)
3. #5368
4. #5369
5. #5370
6. #5371

Feel free to reach out for any clarifications or suggestions ✌️.

# Task details: editing fields

https://user-images.githubusercontent.com/3276087/132259125-da044ffc-1ba9-44f2-b091-c9ba14ae5ac9.mp4
🎨 [See Figma for details](https://www.figma.com/file/c5L9j2mNFiEHynBPmZA39y/Task-context?node-id=479%3A3701).

### Acceptance criteria

- [ ] The task title, assignee, status, due date and team fields can be edited by the user.
- [ ] A border is shown around any of these fields when hovered to indicate that they can be edited.
- [ ] For the task title, clicking the component makes it editable, such as titles in task cards.
- [ ] For the assignee, status, due date, and team fields, clicking them opens the corresponding pop up (see video above).
- [ ] Any updates the user makes are immediately reflected in the UI.

### Estimated effort
32 hrs.
