### ISSUE TITLE
Task details: adding comments

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5368]
This is an implementation issue for #5063.

See related issues for more context:

1. #5366 
2. #5367
3. #5368 (**this issue**)
4. #5369
5. #5370
6. #5371

Feel free to reach out for any clarifications or suggestions ✌️.

# Task details: adding comments

https://user-images.githubusercontent.com/3276087/132259938-02e28477-91ec-4340-8347-ba7f48e98f15.mp4

🎨 [See Figma for details](https://www.figma.com/file/c5L9j2mNFiEHynBPmZA39y/Task-context?node-id=479%3A3701).

### Acceptance criteria
- [ ] Users can use the comment input field to add comments to the task activity thread. 
- [ ] A comment should have similar properties than comments do in meeting comment threads.
- [ ] Comments support a "more menu", intended for actions such as "Pin item" (see related issue)

https://user-images.githubusercontent.com/3276087/132259765-9de0caff-4558-4c20-abd6-27c2ef5129d9.mp4

### Estimated effort
32 hrs.
