### ISSUE TITLE
Task details: search and filtering

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5369]
This is an implementation issue for #5063.

See related issues for more context:

1. #5366 
2. #5367
3. #5368
4. #5369 (**this issue**)
5. #5370
6. #5371

Feel free to reach out for any clarifications or suggestions ✌️.

# Task details: search and filtering

https://user-images.githubusercontent.com/3276087/132260038-6ba7e280-0948-4af0-933b-77980d6f951b.mp4

🎨 [See Figma for details](https://www.figma.com/file/c5L9j2mNFiEHynBPmZA39y/Task-context?node-id=479%3A3701).

### Acceptance criteria
- [ ] Users can perform a live search on the task activity. 
- [ ] When performing a search action, only items that match the search keywords are displayed in the activity thread.
- [ ] Matched keywords are highlighted.
- [ ] Canceling the search action (via the X button or by hitting <kbd>esc</kbd>) returns the activity thread to its normal state.
- [ ] Users can also filter out "detail items" with the `Hide details` toggle. These are items that describe an action and don't include user-generated content, like comments.
- [ ] The button toggles between `Hide details` and `Show details`.

### Estimated effort
24 hrs.
