### ISSUE TITLE
Task details: pinning items

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5370]
This is an implementation issue for #5063.

See related issues for more context:

1. #5366 
2. #5367
3. #5368
4. #5369 
5. #5370 (**this issue**)
6. #5371

Feel free to reach out for any clarifications or suggestions ✌️.

# Task details: pinning items

https://user-images.githubusercontent.com/3276087/132260427-b3c7aa79-fa03-497a-88a3-329670acb363.mp4
🎨 [See Figma for details](https://www.figma.com/file/c5L9j2mNFiEHynBPmZA39y/Task-context?node-id=519%3A4407).

### Acceptance criteria
- [ ] Users can pin any items from the activity thread.
- [ ] Pinning creates a new event that is always at the top of the activity thread. 
- [ ] Pinned items can also be unpinned via the X button ("Unpin item)
- [ ] Pinned items are highlighted and visually distinct from the rest

### Estimated effort
32 hrs.
