### ISSUE TITLE
Spotlight tracking

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#5493]
It'd be interesting to track how users are using the Spotlight as it would give us a clearer understanding of how we can improve it.

### AC: 

With Segment, track how often users are doing the following:

- [ ] Opening the Spotlight 
- [ ] Dragging the source to the results
- [ ] Dragging the results to the source
- [ ] Trying to drag a result to another result

**Comment by avivapinchas** [comment]
I'd suggest one more: using the search field. 

But don't let this request be a blocker 😁

**Comment by nickoferrall** [comment]
I like it! I've pushed an update that tracks whether the user uses the search query. I'm also now sending the search query string to Segment for all events excluding "Opened Spotlight" so that we can see whether the user has searched before dragging a reflection.

**Comment by mattkrick** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/8Kr615RAwE/estimate/4) in Sprint Poker #​​9

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
