### ISSUE TITLE
Create Roadmap for Site Reliability 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5537]
Recently, our app has been unresponsive immediately after we deploy a new version.
This doesn't always happen, but when it does, it's usually at times of high traffic.
We believe this is due to all the clients reconnecting their websockets at about the same time.

At other periods of high load, response times from our GraphQL Executor service will spike, sometimes to over 10 seconds! See https://github.com/ParabolInc/parabol/issues/5189

 From DevSecOps on the last deployment incident:
> latency spiked on nginx from sub 100ms to over 15k ms
then right after that spike active connections went from 1,060 to almost 2k
then I saw a hundreds of auth token requests (authToken) for google auth
redis spiked, but cache hit went down, so it was pulling data from non cache, so that was a rethinkdb spike
during this time the docker process spiked to almost 90%, at this point I think someone restarted docker because it caved

Currently, we're working to replace RethinkDB with Postgres. We're also moving to K8s so we can horizontally scale to multiple GraphQL Executor services. See https://github.com/ParabolInc/parabol/issues/5333 https://github.com/ParabolInc/parabol/issues/3739

As a small product team, we have often prioritized new features over site reliability. However, we're considering dedicating a sprint to improving our backend performance.

A Principal Engineer is responsible for deciding what that work should look like, and how to break it down for Senior Engineers.

Acceptance Criteria:
- [ ] As a Principal Engineer with a team of developers and a 2-week sprint to improve site reliability, what is your course of action? 
- [ ] Create the necessary GitHub issues with Acceptance Criteria that can be assigned to a team of Senior Developers
- [ ] Digging into the codebase, describe how the current flow of how a User connects to the app using a websocket.
- [ ] After understanding how a user connects & the app is deployed, is there any low-hanging fruit that we can immediately address? If so, create a GitHub issue with Acceptance Criteria that can be assigned to a Senior Developer.
- [ ] What other information do you need to see? Server logs from Datadog? Hosting infrastructure? Reach out to the team & we can get you access
- [ ] Is it possible that the latency is caused by our PubSub that powers the GraphQL subscriptions? If so, how can we test that theory?

Estimate: No more than 20 hours. If you don't finish, that's OK! This is more a test of how to work as a team vs. production-ready results.

**Comment by mariogruizdiaz** [comment]
I will continue creating the first issues with acceptance criteria based on the proposed roadmap strategy and I will link them here when I am done!

**Comment by mariogruizdiaz** [comment]
Acceptance Criteria 

- [x]  1 - Depending on the number of available developers for the two weeks sprint, I would suggest starting working on Phase I of my proposal.

- [x] 2 - I created 3 tickets:
 
1. https://github.com/ParabolInc/parabol/issues/5614
2.  https://github.com/ParabolInc/parabol/issues/5615
3.  https://github.com/ParabolInc/parabol/issues/5616
