### ISSUE TITLE
Jira Server Architectural Spec Written

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#5563]
Adding support for Jira Server is [one of our top feature ​requests](https://github.com/ParabolInc/parabol/discussions/5445). We're currently unsure what it would take to implement it. Let's remove this ambiguity.

N.B: @adaniels-parabol can grant the person who takes this issue access to our own version of Jira Server for development

### AC
   - Spec written in GitHub with high-level proposal on how implementation proceed, [see this as an example](https://github.com/ParabolInc/parabol/issues/4412#issuecomment-948003051)
   - After spec reviewed by Review & Maintainer, Epic created and Issues created (including design and implementation issues) and added to Epic
   - Things to consider:
       - Should we create separate Jira integrations under Team→Settings→Integrations and lightweight affordances for disambiguating which integration to add when pushing to a task or the scope phase the first time? (see: #5567)
          -  How might our database schema and graphql schemas need to change? ([see this comment](https://github.com/ParabolInc/parabol/issues/5567#issuecomment-950407873))
          - Should our initial implementation of this integration refactor the `*Auth` tables, or merely start by adding an `IntegrationAuthProvider` table to store the various oauth2 provider configurations?
       - Are all of the API calls identical between server and cloud?
       - Can we use Atlassian's new GraphQL API (see & possibly close #5539)

### EE
   - 21 hours

**Comment by Dschoordsch** [comment]
# Jira Server Integration Proposal

## Overview
Jira Server is an onsite ticket system which Atlassian plans to fade out in favour of their Atlassian Cloud offering https://www.atlassian.com/migration/assess/journey-to-cloud There are no new features planned after January 2022.

### API
**REST** https://developer.atlassian.com/server/jira/platform/rest-apis/
Jira Server does not offer GraphQL.

### Jira Server Application
An administrator can add an **OAuth 1.0a** application.
https://developer.atlassian.com/server/jira/platform/oauth/#step-1--configure-jira
The administrator needs to create a private/public key pair and then enter
* Shared secret
* Request Token URL
* Access token URL
* Authorize URL
* Consumer key
* Consumer name
* Public key

in Jira to add Parabol as application. In Parabol we need
* Jira Home URL
* Private key
* a name (in case there are multiple Jira Server instances added)

Since this is a bit more involved, we need to provide a direct link to the documentation, or in the future go further and make it a wizard type dialog on our end which generates public/private key pair automatically and presents prefilled dialog to user to only copy and paste.

### Integration Provider

Following the proposal of #5594 we have two variants of adding the Jira Server integration provider: team scope or organization scope.
### Team scoped
* Pro
  * more granular
* Con
  * a lot more work for the team lead
  * not every team lead will get admin rights on Jira
  * most companies will probably not have multiple Jira server instances running
### Organization scoped
* Pro
  * only one time setup
  * most likely matches the one Jira instance companies are running
  * easier to organize administrator rights to set it up
* Cons
  * if there are multiple Jira instances in an organization for different teams, all of these need to be added and everyone sees all instances

This is very clear in favour of **organization scope**.

Users within the organization with Jira Server being set up would then have an option to connect to it similar to other integrations.
![Screenshot from 2021-12-13 09-18-58](https://user-images.githubusercontent.com/7331043/145812712-8ce8ed60-0ec2-4f40-8574-8ef95efac7d0.png)
If there is more than one integration added, it would show all of them. Connecting starts the OAuth flow. The token is valid for 5 years and there is **no refresh token**.

**Comment by Dschoordsch** [comment]
# Implementation steps

## Integration provider setup
Since the setup is a bit more involved and we don't have a UI yet where the user could add integrations for the organization, I propose adding it manually for enterprise customers first with a similar process like we use for SAML, i.e. our sales folks guide them through the setup.

## Feature flag
The feature will only be available when a supervisor adds the provider to the organization. There is no need for a separate feature flag.

## Tasks version 1
* [ ] Jira Server integration provider
* [ ] Jira Server create task integration
* [ ] Jira Server sprint poker vote to comment
* [ ] Jira Server sprint poker vote to field

**Comment by jordanh** [comment]
> Since the setup is a bit more involved and we don't have a UI yet where the user could add integrations for the organization, I propose adding it manually for enterprise customers

I concur completely!

**Comment by Dschoordsch** [comment]
@BartoszJarocki could you please take a look if I forgot anything fundamental?

**Comment by Dschoordsch** [comment]
Closing this as there shouldn't be any more surprises for Version 1.
