### ISSUE TITLE
Stand-up v1 milestone drafted

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5609]
In which we stub out a stand-up v1 milestone…

This is a continuation of the output from #5460 and can be found [in Notion](https://www.notion.so/parabol/Stand-up-Proposal-98d513d6593b4b64ad797580869484c3)

This issue is where I’ll start to break down the work. I’ll probably close it later, and we can point back to it from separate, better defined issues.

The goal is to ship a minimal v1 of a stand-up activity. I’ll attempt to stub out the work as issues that are meant to be both the smallest possible units of work, and deemed necessary to ship a first version. We’ll begin by learning, showing a prototype to 5 customers. We can fill in or update the acceptance criteria as we learn.

---

## Opportunities to build a testable or workable UI little by little
- Start with a prototype constrained to a v1 (exclude deferred elements) to gather feedback from 5 customers. This shouldn’t delay scoping or design work
- Build an activity interface behind a feature flag where folks can add responses
- Stubbed out an end-to-end experience behind a feature flag:
  - Stubbed new meeting view, stubbed meeting card, stubbed summary, stubbed meetings settings side sheet (see below in the distinct tasks)
  - No thread, no recurring, no chat notifications yet
- Add the thread to the basic interface
- Add recurring to the views (new meeting dialog options, meeting logic, meeting settings)
- Updated the new meeting card
- Updated the timeline summary card
- Add chat notifications for Slack and Mattermost

### Before we stub out the end-to-end experience
- We would need a first version of the new meeting dialog #5589 before we stubbed in the end-to-end experience of a stand-up behind a meeting flag

### Key features to include in the first version
- The stand-up is in the [new meeting dialog](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26495)
- A single, editable prompt per one-time or recurring activity
- The option to dial in recurring instances on a weekly rotation (i.e. set to recur any day of the work week)
- Chat integrations, at least with Slack, but we should throw in Mattermost while we’re in there
- [One response card and associated thread per participant](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26497)

---

## Distinct tasks by category
This is the work required to ship a first version, but there are options on how to test working code behind a feature flag.

### Stand-up prototype tested
What can we learn before we build? This shouldn’t block scoping work or the bulk of design work. Here we roughly take these actions as a research effort
- Minimal prototype created #5635 
- Tested prototype with 5 customers
- Identified takeaways
- Integrated takeaways into the work below

### Stand-up UX scoped
What are the AC in terms of user experience? What do the v1 designs include? Here we write a set of AC per bullet
See #5637
- [New meeting view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26495) scoped
  - Scoped the UX of a recurring series
  - Scoped the UX of adding a chat integration
- Stand-up phase view scoped
- Stand-up response card scoped
- Stand-up thread scoped
- Stand-up meeting card scoped
- Stand-up summary card scoped
- Stand-up chat notifications scoped
- [Meeting settings side sheet](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26499): editing an existing stand-up (changing the name, prompt, recurring settings, integration settings)

### Stand-up UI designed
What does the first version look like? Here we design a view with various states for each bullet
- [Stand-up phase view designed](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26497)
- Stand-up response card designed
- Stand-up thread designed
- Stand-up [new meeting view designed](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26495)
- Stand-up meeting card designed
- Stand-up summary card designed
- Stand-up chat notifications designed
- [Meeting settings side sheet](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26499): editing an existing stand-up (changing the name, prompt, recurring settings, integration settings)

### Architecture scoped
How are the components defined in our system? Here we write out proposals for how to handle the following:
- Scoped expected types to support a stand-up activity
- Scoped expected mutations to support a stand-up activity
- Scoped logic and patterns to support recurring stand-up activities

### Added types
Do we have the necessary building blocks? Here we add each type to our codebase:
- Team prompt activity (meeting with name, team, prompt, recurring settings, integration settings)
- Respond phase
- Respond phase prompt
- Response card object
- Recurring series object

### Wrote mutations
Do we have the mutations needed to enable the interface? Here we write mutations for the following:
- Team prompt activity (meeting)
  - Start
  - Complete
  - Delete (removes the meeting without a summary, for Parabol admins for now)
- Team prompt activity editing
  - Edit name
  - Edit prompt
  - Edit recurring settings
  - Edit integration settings
- Response card CRUD by author
- Response reactions (participants can add/remove reactions)
- Recurring series mutations

### Built main phase UI without thread
How do we build a working phase interface? Here we make a first pass at the main UI:
- Layout includes top bar with activity meta, prompt, and team hub
- Adds a response card
- Adds author input states on response card
- Adds a grid of response cards
- Adds empty state meta for past participants

### Stubbed out the workflow
How can we test something scrappy, end to end, behind a feature flag? Here we ‘sketch’ in basic components quickly so that experience can be end to end:
- Adds a feature flag that can be set by user. It adds the stubbed out version to the new meeting dialog. Once a meeting is created anybody on that team can see the meeting, the meeting card, and the summary
- Stubs out the stand-up view in the new meeting dialog (can edit the prompt)
- Stubs out the stand-up meeting card. Folks can join. Folks can navigate to meeting settings side sheet
- Stubs out the stand-up summary card. Folks can navigate to a completed meeting and see the responses
- Stubs out [meeting settings side sheet](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26499) (first pass: can edit name, prompt, or end the meeting)

### Added stand-up thread UI
Let’s add threads to the interface
- Adds thread to the interface

### Added recurring logic
How does this open and close meetings automatically? We add this feature to the stubbed out experience:
- Adds recurring logic to stand-up activity
- Adds recurring settings UI to stand-up view in new meeting dialog
- Adds recurring settings to meeting settings side sheet

### Updated the dashboard UI
Here we can refine the dashboard components in order to ship:
- Updates the meeting card to latest designs
- Updates the summary card to the latest designs

### Added chat integrations
Now that we having a working first version, let’s add the chat notifications! Here we add the settings UI and build the notifications themselves:
- Adds inline chat integration settings component to new meeting dialog
- Adds inline chat integration settings component to meeting settings side sheet
- Adds a first created notification for chat (Slack / Mattermost)
- Adds a participation reminder notification for chat (Slack / Mattermost)
- Adds a summary reminder notification for chat (Slack / Mattermost)

---

## Deferred, a set of possible enhancements
- Moved check-ins behind a feature flag
- [Focus editing view](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26498): author editing opens in a focus view, allowing an Inspirations panel to open up in the future
  - Designed focus view UI
  - Added focus view UI
- [Inspiration sidebar](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26498): folks can see their work in integrated services to inspire their responses
  - Designed inspiration panel in the focus editing view
  - Added inspiration sidebar to stand-up focus editing view
- Quick historical navigation: users can navigate to past instances with a control at the top of the activity view
  - Designed quick navigator
  - Added quick navigator UI
  - [See the ‘Tue Oct 5’ control label in this concept](https://www.figma.com/file/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?node-id=682%3A26497)
- Thread notifications: users are notified when somebody comments on their card or in a thread that they’ve participated in
  - Designed thread notifications
  - Added thread notifications
- Can response with GIFs
  - Designed GIF responses
  - Added GIF responses
- A separate activity can be added to the new meeting dialog. This can be a watercooler or icebreaker activity. Parabol can provide default lists. Folks can clone and crud their own lists. Each time the activity opens it pulls a random prompt from the list. Perhaps we make a complete cycle through known prompts before repeating
  - Prototype water cooler activity
  - Designed templated prompt lists
  - Scoped templated prompt lists
  - Shipped new activity type

**Comment by ackernaut** [comment]
My next steps:
- Clarified and edited here based on questions and feedback
- Scoped the UX of the end-to-end experience as written AC
- Wrote prototype issue and some next design issues
- Planned next scrappy prototype feedback effort in Notion (and begin recruiting 5 customers)

**Comment by ackernaut** [comment]
- [x] Added feature flag (*FF) for beta users
- [x] Prototype created
## New activity type created
**Goal**: beta users can start and end a team prompt activity; they see a card on the meetings view
- [ ] Discussed recurring team prompt activity architecture
- [ ] Decided and documented key team prompt activity architecture details
- [ ] Created a team prompt activity data type
- [ ] Created a start and end mutation for team prompt activity
- [ ] Added a placeholder meeting card to meetings view behind the feature flag
- [ ] Added a placeholder start view in existing new meeting view behind the feature flag
- [ ] Designed the team prompt activity card
## New activity prompt added
**Goal**: folks can edit a prompt for the activity
- [ ] Prompt data type added for team prompt activity
- [ ] Placeholder input added to new meeting view; beta users can edit prompt
- [ ] Route created for team prompt activity; folks can visit the activity when opened and see a read-only prompt
- [ ] Single prompt editor designed for new meeting dialog
- [ ] Placeholder inline editing added to prompt within open team prompt activity
## Response card added
**Goal**: folks can add a response and see others respond on the grid
- [ ] Created a response data type
- [ ] Created a response mutation
- [ ] Created a placeholder input for adding responses
- [ ] Laid out a placeholder grid of inputs
- [ ] Designed response input & editing and layout grid
## Threads added
**Goal**: users can engage responses via thread and reaction emoji
- [ ] Responses can have their own thread object
- [ ] Thread has original response card content at the top
- [ ] Users can tap on a response to open a thread
- [ ] Users can add comments or tasks in the thread
- [ ] Reaction emoji added to response cards and response card top content
- [ ] Designed reactions on cards and thread with response card content at top
## Non-recurring chat notifications added
Goal: when opening an activity, beta users can select a channel to receive a notification
- [ ] For non-recurring prompt activities, sends an open notification when opened
- [ ] For non-recurring prompt activities, sends a closed notification when closed
- [ ] Placeholder chat integration controls added to existing new meeting view
## Recurrence
Goal: beta users can specify recurrence; open activities update automatically to reflect the pattern
- [ ] Data types updated to support recurring patterns
- [ ] Mutations created to support recurring selections
- [ ] Placeholder recurrence controls added to the start meeting view
## Chat notifications added for recurrence
- [ ] Chat notifications types created to include a time to send
- [ ] Placeholder UI supports configuring chat for recurring activities in existing new meeting view
- [ ] Designed chat configuration in new meeting dialog
## New meeting dialog added
- [ ] MVP implemented. Dialog can open over current view context
- [ ] Team prompt activity view added to new meeting dialog. Placeholder controls are refined to meet UX and UI
- [ ] Activity editing dialog can open over current view contet

**Comment by ackernaut** [comment]
Just jotting down notes from talking with Matt, an even more barebones MPV:
- No start meeting dialog (use the existing start meeting pattern)
- No editable prompt (we have a fixed prompt)
- No recurrence (one-time activities only)
- No day navigator (one-time activities only)
- Editing responses inline - no inspirations or focus mode for editing
- Yes to threads
- Yes to reactji on cards
- Meeting card is the way to end for now (no settings view in activity)
- Closed meeting (can still edit TBD?)
- Cheap summary card on the timeline upon ending one-time activity (points to closed meeting end-point)
