### ISSUE TITLE
Azure DevOps Integration Proposal

### ISSUE THREAD

**Issue by bobjac** [ParabolInc/parabol#6125]
# Azure DevOps Integration Proposal

## Overview
Azure DevOps is a devops service owned by Microsoft that comes in 2 flavors:

- Azure DevOps Services : a cloud-based service hosted by Microsoft
- Azure DevOps Server : an premises implementation (formerly Team Foundation Server)

### API
REST [https://docs.microsoft.com/en-us/rest/api/azure/devops/?preserve-view=true&view=azure-devops-rest-7.1&viewFallbackFrom=azure-devops-rest-6.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/?preserve-view=true&view=azure-devops-rest-7.1&viewFallbackFrom=azure-devops-rest-6.1)
Azure Devops does not offer GraphQL.

### Azure DevOps Cloud Service
Integrating Azure DevOps into Parabol will require calling the Azure DevOps REST APIs.  Authenticating these REST calls will require configuration steps for the Azure DevOps administrator.  These steps will be slightly different depending on the authentication mode chosen as described in the proposal of [Link to other issue]

Since the integration provider setup is somewhat involved, I propose adding it manually for the first version similar to Issue [#5563](https://github.com/ParabolInc/parabol/issues/5563).

### Version 1 (push tasks to integration)

- [x] [Azure DevOps: integration provider](https://github.com/ParabolInc/parabol/issues/6124)
- [x] [Azure DevOps: Azure DevOps PAT Token Flow](https://github.com/ParabolInc/parabol/issues/6136)
- [x] [Azure DevOps: Rest Manager](https://github.com/ParabolInc/parabol/issues/6137)

**Comment by bobjac** [comment]
These were implemented for v1.
