### ISSUE TITLE
MS Teams integration DRAFT

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6298]
## Current state
We have to notification integrations: Slack and Mattermost. Slack has more options but should not be used as a pattern, it stores data in rethink (deprecated) and has some individual mutations. Mattermost follows current best practices at Parabol.

## Authentication/Authorization
Slack uses OAuth, Mattermost uses webhooks.

Authentication data should be stored in "IntegrationProvider" (provider per tenant) and "TeamMemberIntegrationAuth" (individual users tokens) tables. There are `addIntegrationProvider`/`removeIntegrationProvider` and `addTeamMemberIntegrationAuth`/`removeTeamMemberIntegrationAuth` mutations already which should be adopted.

Flow is started from the "...ProviderRow"
https://github.com/ParabolInc/parabol/blob/eb295331feba7e2534c48012d252c2a52b802905/packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
https://github.com/ParabolInc/parabol/blob/f5de4e3ec939a8ff4c94150dc31a282dc5bdaec7/packages/client/modules/teamDashboard/components/ProviderRow/SlackProviderRow.tsx
which for Slack starts the OAuth flow which comes back to the "...ClientManager"
https://github.com/ParabolInc/parabol/blob/8dbff9b4c6d19467c96b323be63f61e2926dc0a5/packages/client/utils/SlackClientManager.ts
Above mentioned mutations should be adapted for this.

## Notifications
We currently have 4 notifications which can be configured individually (Slack) or all go to the same channel (Mattermost). These are in the process of being refactored which should simplify adding new notifications
* #6262 

## Implementation Steps

- [ ] [MS Teams: Integration Provider](https://github.com/ParabolInc/parabol/issues/6375)
- [ ] [MS Teams: List Joined Teams](https://github.com/ParabolInc/parabol/issues/6376)
- [ ] [MS Teams: Meeting Event Notifications](https://github.com/ParabolInc/parabol/issues/6377)
