### ISSUE TITLE
Recurrence: introduce stable link to a meeting series

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#7450]
Epic grouping work related to [Product brief: Recurrence - stable link](https://www.notion.so/parabol/Product-brief-Recurrence-stable-link-b5cd892d169d49e6a148e3cea92f3360) 🔒 
[Initial Scope](https://www.notion.so/parabol/Scope-Definition-Recurrence-Stable-Link-v0-ec07677a12534f3c87212f70287bfeb7) 🔒 

### Design tasks

- [x] #7481
- [x] #7482
- [x] #7483
- [x] #7484
- [x] https://github.com/ParabolInc/parabol/issues/7701

### Implementation tasks
- [x] https://github.com/ParabolInc/parabol/issues/7700
- [x] https://github.com/ParabolInc/parabol/issues/7702
- [x] https://github.com/ParabolInc/parabol/issues/7703
