### ISSUE TITLE
Checkout Flow: add tracking

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#7813]
Discuss with @tghanken which events we would like to capture. 

Previously we were tracking when the credit card model was opened, but landing on the Organization page might give us less signal that a user may be interested in upgrading.

Perhaps we measure when a user:
- visits the org page
- begin adding credit card details
- click on a plan
- click upgrade

### AC

- [ ] Discuss what to track with Taylor
- [ ] Implement tracking for the relevant events

**Comment by tghanken** [comment]
I think you have the right events outlined already! One clarifying question around the design: Can payment details be added independently of adding/changing plans? If so, we'd want events when they start adding payment details, and when they save the card details.

We'd also want to track a "Modify Organization Billing Leaders" event when users add/remove/edit the list of billing leaders.

I think the list of events looks like this:
- [x] Organization page view (automatically handled by Segment)
- [ ] "Plan Tier Selected" event w/ a tier parameter showing the selected plan tier
- [ ] "Payment Details Started" event
- [ ] "Payment Details Completed" even on CC details save
- [x] "Organization Upgraded" - should already be emitted when the upgrade completes, don't need to add anything
- [ ] "Billing Leader Modified" w/ a modification type enum (add/remove/update) and the userId of the modified leader

**Comment by tghanken** [comment]
> Yeah, I think we'll need the option to edit card details that have previously been submitted, if that's what you're referring to?

Yeah, exactly.  I think if we emit those payment details events each time they edit, that should be sufficient!
