### ISSUE TITLE
Integration Control at Organization and Team Levels

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#8352]
Design and implement a solution to manage Parabol integrations at both organization and team levels. The solution should allow for control over which integrations are enabled or disabled at an organization level and at a team level, with a default setup configured by the organization. The enabled or disabled status of the integrations should be stored in Postgres.

**Requirements:**
- Organizational Level Control: Enable or disable any integration for the entire organization and all its teams.
- Team Level Control: Enable or disable integrations on a team-by-team basis, provided these integrations are allowed by the organization.
- Default Integrations: At an organization level, define default settings for integrations, specifying which are enabled or disabled by default.

**Tasks:**
- [ ] Schema Update: create a schema in PostgreSQL to store the enabled or disabled status of integrations at both organization and team levels.
- [ ] Organizational Level Control: allows an organization's billing leader to enable or disable any integration for the entire organization and all its teams.
- [ ] Team Level Control: allows a team's leader to enable or disable integrations for their team, provided these integrations are allowed by the organization.
- [ ] Default Integrations Control: allows an organization's billing leader to specify which integrations are enabled or disabled by default.

**Comment by jordanh** [comment]
Assigning this one to the self-serve squad as I know that @avivapinchas is looking into what we might prioritize in terms of adding enterprise administrative features. I don't expect us to prioritize this one quickly, but I could also see us picking this one up in the near future when we get our instance of Parabol to production at Platform One—I imagine this will be a common need
